import { Project } from '@/types/project';

export const projectsData: Project[] = [
  {
    id: 1,
    title: 'AI-Powered Robotics Navigation',
    description: 'A robotics project using AI to navigate obstacles autonomously. This project implements advanced computer vision and machine learning algorithms to enable robots to make intelligent decisions in real-time.',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80',
    chapterId: 'RAS',
    author: 'John Doe',
    link: 'https://ieeehelwan.org/projects/ai-robotics',
    createdAt: '2025-11-20T14:30:00Z',
  },
  {
    id: 2,
    title: 'Smart Power Grid Simulation',
    description: 'Simulation of smart power grids for energy efficiency. This comprehensive system models renewable energy integration and load balancing for sustainable power distribution.',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80',
    chapterId: 'PES',
    author: 'Jane Smith',
    link: 'https://ieeehelwan.org/projects/power-grid',
    createdAt: '2025-11-19T09:15:00Z',
  },
  {
    id: 3,
    title: 'Blockchain for Healthcare',
    description: 'Decentralized patient record management system using blockchain technology to ensure data privacy and security in medical institutions.',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80',
    chapterId: 'CS',
    author: 'Ahmed Hassan',
    link: 'https://ieeehelwan.org/projects/blockchain-health',
    createdAt: '2025-11-18T16:45:00Z',
  },
  {
    id: 4,
    title: 'Women in STEM Mentorship Platform',
    description: 'A digital platform connecting female students with industry mentors to promote diversity and inclusion in technology fields.',
    image: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=800&q=80',
    chapterId: 'WIE',
    author: 'Sara Mohamed',
    createdAt: '2025-11-17T11:20:00Z',
  },
  {
    id: 5,
    title: 'Industrial IoT Monitoring System',
    description: 'Real-time monitoring and predictive maintenance system for industrial equipment using IoT sensors and data analytics.',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80',
    chapterId: 'IAS',
    author: 'Omar Khaled',
    link: 'https://ieeehelwan.org/projects/iot-industrial',
    createdAt: '2025-11-16T13:30:00Z',
  },
  {
    id: 6,
    title: 'Medical Imaging AI Diagnosis',
    description: 'Deep learning model for automated medical image analysis to assist doctors in early disease detection and diagnosis.',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&q=80',
    chapterId: 'EMBS',
    author: 'Nour Ibrahim',
    link: 'https://ieeehelwan.org/projects/medical-ai',
    createdAt: '2025-11-15T10:00:00Z',
  },
  {
    id: 7,
    title: '5G Antenna Design Optimization',
    description: 'Advanced antenna design for 5G networks with improved signal coverage and reduced interference using optimization algorithms.',
    image: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=800&q=80',
    chapterId: 'MTT-S',
    author: 'Karim Youssef',
    createdAt: '2025-11-14T14:15:00Z',
  },
  {
    id: 8,
    title: 'Cybersecurity Training Platform',
    description: 'Interactive platform for cybersecurity education featuring hands-on labs, CTF challenges, and real-world security scenarios.',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
    chapterId: 'CS',
    author: 'Layla Ahmed',
    link: 'https://ieeehelwan.org/projects/cyber-training',
    createdAt: '2025-11-13T15:45:00Z',
  },
  {
    id: 9,
    title: 'Autonomous Drone Delivery System',
    description: 'Drone-based delivery system with autonomous navigation, obstacle avoidance, and efficient route planning algorithms.',
    image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&q=80',
    chapterId: 'RAS',
    author: 'Youssef Ali',
    link: 'https://ieeehelwan.org/projects/drone-delivery',
    createdAt: '2025-11-12T09:30:00Z',
  },
  {
    id: 10,
    title: 'Renewable Energy Management System',
    description: 'Smart system for managing renewable energy sources including solar panels and wind turbines with optimal energy distribution.',
    image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&q=80',
    chapterId: 'PES',
    author: 'Mona Fathy',
    createdAt: '2025-11-11T12:00:00Z',
  },
];
