import { Project } from '@/types/project';

export const projectsData: Project[] = [
  {
    id: 1,
    title: 'An Amazing Firefighting Robot',
    description: 'The IEEE RAS chapter introduces amazing projects using Arduino. This robot utilizes three flame sensors to detect the presence of a fire, after that it goes to make fire down using a BLDC pump hooked to servo motor to squeeze water on fire at degrees from 30 to 150.',
    image: '/assets/projects/fireFighting.jpg',
    subImages: [
      '/assets/projects/fireFighting.jpg',
      '/assets/projects/fireFighting2.jpg',
    ],
    chapterId: 'RAS',
    author: 'RAS',
    // link: 'https://ieeehelwan.org/projects/ai-robotics',
    createdAt: '2025-11-20T14:30:00Z',
  },
  {
    id: 2,
    title: 'LED Stacking Game',
    description: 'An interactive electronic game where players stack moving LED blocks with precise timing. Each row must align perfectly with the one below it , any misalignment causes the block to shrink, reducing the number of LEDs available. The game continues until the player loses all LEDs. Designed and built from scratch, it combines a custom mechanical enclosure with an Arduino-based control circuit and LED matrix display, showcasing the integration of mechanical design, electronics, and programming in a fun, engaging way.',
    image: '/assets/projects/ledStackingGame.jpg',
    subImages: [
      '/assets/projects/ledStackingGame2.jpg',
      '/assets/projects/ledStackingGame.jpg',
    ],
    chapterId: 'RAS',
    author: 'RAS',
    // link: 'https://ieeehelwan.org/projects/power-grid',
    createdAt: '2025-11-19T09:15:00Z',
  },
  {
    id: 3,
    title: 'Color guess 404 -',
    description:"This game shows a pattern of colored lights, and the player must repeat the pattern by pressing the matching buttons. When the game starts, the player presses any button, and the LCD shows “Color Guess 404!” to begin. The game starts at level one. It flashes one random color. The player must press the button for that color. If correct, the game moves to the next level and adds one more color to the sequence, making it longer each time.",
    image: '/assets/projects/colorGuess.jpg',
    subImages: [
      '/assets/projects/colorGuess.jpg',
    ],
    chapterId: 'RAS',
    author: 'RAS',
    // link: 'https://ieeehelwan.org/projects/blockchain-health',
    createdAt: '2025-11-18T16:45:00Z',
  },
  {
    id: 4,
    title: 'Smart Score Basket',
    description: 'Smart Score Basket is a mini basketball arcade system that automatically tracks score and game time using sensors and a microcontroller. Each time the ball passes through the hoop, the timer starts and the player&apos;s score increases.When time runs out, a buzzer alerts the player and the LCD displays the final score. The system also checks for a new high score, adding a competitive and fun experience. This project combines sensors, hardware, and programming to create a compact and interactive basketball game.',
    image: '/assets/projects/scoreBasket.jpg',
    subImages: [
      '/assets/projects/scoreBasket.jpg',
    ],
    chapterId: 'RAS',
    author: 'RAS',
    createdAt: '2025-11-17T11:20:00Z',
  },
  {
    id: 5,
    title: ' Questions game',
    description: 'The Questions game is a two-player game. Rules are simple; questions are displayed on an LCD and the player who knows the answer first pushes the red button then he or she must push the button associated with the correct answer in less than two seconds. The player with more correct answers wins the game. The game was implemented by RAS members using Arduino microcontroller that controls both the LCD and the buttons.',
    image: '/assets/projects/questionGame.jpg',
    subImages: [
      '/assets/projects/questionGame.jpg',
    ],
    chapterId: 'RAS',
    author: 'RAS',
    // link: 'https://ieeehelwan.org/projects/iot-industrial',
    createdAt: '2025-11-16T13:30:00Z',
  },
  {
    id: 8,
    title: '4DOF Arduino Pick and Place Robotic Arm',
    description: '4DOF Arduino Pick and Place Robotic Arm This is a versatile 4 Degrees of Freedom (4DOF) robotic arm designed specifically for educational and prototype pick-and-place tasks. It is fully controlled by an Arduino microcontroller, making it an accessible platform for exploring robotics and basic kinematics. The four axes of movement (Base, Shoulder, Elbow, and Gripper) allow it to precisely manipulate small objects within its working envelope.The arm&apos;s motion is driven by a combination of servo motors, strategically chosen for different roles: robust MG995 servos handle the high-torque movements of the Base and Shoulder joints; SG5010 servos manage the Elbow joint; and a smaller SG90 provides swift, light control for the Gripper end-effector. This component setup ensures a balance of power, weight, and precision, making it an ideal model for implementing simple automation routines.',
    image: '/assets/projects/roboticArm.jpg',
    subImages: [
      '/assets/projects/roboticArm.jpg',
    ],
    chapterId: 'RAS',
    author: 'RAS',
    // link: 'https://ieeehelwan.org/projects/cyber-training',
    createdAt: '2025-11-13T15:45:00Z',
  },
  {
    id: 9,
    title: 'Autonomous Drone Delivery System',
    description: 'Drone-based delivery system with autonomous navigation, obstacle avoidance, and efficient route planning algorithms.',
    image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&q=80',
    subImages: [
      '/assets/projects/fireFighting.jpg',
      'https://ieeehelwan.org/projects/ai-robotics',
      'https://ieeehelwan.org/projects/ai-robotics',
    ],
    chapterId: 'RAS',
    author: 'Youssef Ali',
    link: 'https://ieeehelwan.org/projects/drone-delivery',
    createdAt: '2025-11-12T09:30:00Z',
  },
  {
    id: 10,
    title: 'Renewable Energy Management System',
    description: 'Smart system for managing renewable energy sources including solar panels and wind turbines with optimal energy distribution.',
    image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&q=80',
    subImages: [
      '/assets/projects/fireFighting.jpg',
      'https://ieeehelwan.org/projects/ai-robotics',
      'https://ieeehelwan.org/projects/ai-robotics',
    ],
    chapterId: 'PES',
    author: 'Mona Fathy',
    createdAt: '2025-11-11T12:00:00Z',
  },
];
